version: '3.7'

services:

  postgres_database:
    image: postgres:latest
    container_name: postgres_database
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres_database
    ports:
      - "5432:5432"
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    container_name: multipurpose_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    restart: on-failure
    image: multipurpose_api
    environment:
      - "PORT=8888"
      - "DB_HOST=postgres_database"
      - "DB_PORT=5432"
      - "DB_NAME=postgres_database"
      - "DB_USER=postgres"
      - "DB_PASSWORD=admin"